first commit (#2)
appwex/izzy-health pull request #13
Opened 2022-12-16 07:29 UTC by tehseen01

# Description

- added navbar under component
- added style in same folder

Fixes # (#2)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# preview

![Screenshot 2022-12-16 125541](https://user-images.githubusercontent.com/86504467/208045848-84c968af-894a-4195-bcb5-b0bc36e43da8.png)
![Screenshot 2022-12-16 125719](https://user-images.githubusercontent.com/86504467/208045837-2af17c3e-97f9-4201-bd27-09892957a037.png)
![Screenshot 2022-12-16 125641](https://user-images.githubusercontent.com/86504467/208045851-9357e351-f6a0-4eb8-97dd-b4b789afbd04.png)

2022-12-16 08:30 UTC, aftabrehan requested changes
Excellent PR @tehseen01 💪🚀 💯

Just needs minor fixes and it's good to go 🚀

2022-12-16 08:30 UTC, aftabrehan commented on src/components/navbar/navbar.js
> +        <span></span>
```
                      <span />
                      <span />
                      <span />
```

2022-12-16 08:30 UTC, aftabrehan commented on src/components/navbar/navbar.module.scss
> +@import '/src/styles/common.scss';
@import 'styles/common';

2022-12-16 08:30 UTC, aftabrehan commented on src/components/navbar/navbar.js
> +      <nav className={`${stl.navbar} ${expendNav ? stl.expend : ''}`}>
Use `clsx` here, see the example in button component.

2022-12-16 15:28 UTC, mrxshinji approved these changes
All good. Thanks

2022-12-17 04:29 UTC, aftabrehan approved these changes
Excellent PR, @tehseen01 💪 🚀 💯

2022-12-17 04:29 UTC, merged